
export const FORM = {
    LOGIN:{
        initialValues:{
            username:"",
            password:""
        },
        inputs:[
            {   
                id:"001",
                label:"username",
                name:"username",
                type:"text"
            },
            {   
                id:"002",
                label:"password",
                name:"password",
                type:"password"
            },
        
        ]
    },
    SIGNUP:{
        initialValues:{
            fullName:"",
            username:"",
            email:"",
            password:""
        },
        inputs:[
            {   
                id:"001",
                label:"fullName",
                name:"fullName",
                type:"text"
            },
            {   
                id:"002",
                label:"username",
                name:"username",
                type:"text"
            },
            {   
                id:"003",
                label:"email",
                name:"email",
                type:"email"
            },
            {   
                id:"004",
                label:"password",
                name:"password",
                type:"password"
            },
        ]
    }
}