import { useTranslation } from 'next-i18next';
import Head from 'next/head'
import { Fragment } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Layout from '../../components/Layout';
import HomeContainer from '../../features/Home/HomeContainer';

export default function Home() {

  const { t } = useTranslation();

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> {t("restaurants")} | Foody Delivery</title>
      </Head>
      <Layout>
        <h1>Restaurant</h1>
      </Layout>
    </Fragment>
  )
}


export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'menu'])),
    },
  };
}