import { useTranslation } from 'next-i18next';
import Head from 'next/head'
import { Fragment } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import dynamic from 'next/dynamic'

const AboutContainer = dynamic(() => import('../../features/About/AboutContainer'))
const Layout = dynamic(() => import('../../components/Layout'))

export default function Restaurants() {

  const { t } = useTranslation("menu");

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> {t("about us")} | Foody Delivery</title>
      </Head>
      <Layout>
        <AboutContainer/>
      </Layout>
    </Fragment>
  )
}


export async function getServerSideProps({ locale }) {
  let languages = { ...await serverSideTranslations(locale, ['common', 'menu']) }
 
   return {
     props: {
      ...languages
     },
   };
 }