import { useTranslation } from 'next-i18next';
import Head from 'next/head'
import { Fragment } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import dynamic from 'next/dynamic'
import NotFoundContainer from '../../features/NotFound/NotFoundContainer';

// const NotFoundContainer = dynamic(() => import('../../features/NotFound/NotFoundContainer'))
const Layout = dynamic(() => import('../../components/Layout'))

export default function NotFoundPage() {

  const { t } = useTranslation();

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> {t("restaurants")} | Foody Delivery</title>
      </Head>
      <Layout>
        <NotFoundContainer/>
      </Layout>
    </Fragment>
  )
}


export async function getStaticProps({ locale }) {
  let languages = { ...await serverSideTranslations(locale, ['common', 'menu']) }
 
   return {
     props: {
      ...languages
     },
   };
 }