import { useTranslation } from 'next-i18next';
import Head from 'next/head'
import { Fragment } from 'react'
import Layout from '../components/Layout'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';


export default function Home() {

  const { t } = useTranslation();

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> {t("home")} | Foody Delivery</title>
      </Head>
      <Layout>

      </Layout>
    </Fragment>
  )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'menu'])),
    },
  };
}