import Head from 'next/head'
import { Fragment } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import dynamic from 'next/dynamic';

const Layout = dynamic(() => import('../components/Layout'))
const HomeContainer = dynamic(() => import('../features/Home/HomeContainer'))

 const HomePage = () => {

  const { t } = useTranslation("menu");

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> {t("home")} | Foody Delivery</title>
      </Head>
      <Layout>
        <HomeContainer />
      </Layout>
    </Fragment>
  )
}

export default HomePage

export async function getServerSideProps({ locale }) {
  let languages = { ...await serverSideTranslations(locale, ['common', 'menu']) }

  return {
    props: {
      ...languages
    },
  };
}